#!/bin/bash

# install pacman packages
sudo pacman --needed -S \
    archlinux-xdg-menu  \
    awesome             \
    base-devel          \
    bash-completion     \
    cmake               \
    feh                 \
    ffmpeg              \
    git                 \
    gnu-free-fonts      \
    gparted             \
    htop                \
    imagemagick         \
    iw                  \
    iwd                 \
    lib32-mesa          \
    lib32-vulkan-radeon \
    linux-headers       \
    liquidctl           \
    lsb-release         \
    man-db              \
    man-pages           \
    mesa                \
    mlocate             \
    mtools              \
    noto-fonts          \
    noto-fonts-emoji    \
    ntfs-3g             \
    openssh             \
    p7zip               \
    pipewire-alsa       \
    pipewire-jack       \
    pipewire-pulse      \
    reflector           \
    tk                  \
    unzip               \
    vim                 \
    vulkan-radeon       \
    wget                \
    wireplumber         \
    xarchiver           \
    xcompmgr            \
    xdg-user-dirs       \
    xdg-utils           \
    xf86-video-amdgpu   \
    xorg-xrandr         \
    xscreensaver        \
    xterm               \
    zip
