#!/bin/bash

# install paru packages
paru --needed -S                \
    bulky                       \
    feishin-bin                 \
    freetube-bin                \
    heroic-games-launcher-bin   \
    mcomix                      \
    mkinitcpio-firmware         \
    mullvad-browser-bin         \
    mullvad-vpn-bin             \
    parsec-bin                  \
    protonup-qt                 \
    sgdboop-bin                 \
    slack-desktop               \
    steamlink                   \
    tiny-media-manager          \
    vscodium-bin                \
    xfe                         \
    yed                         \
    zoom

# set default file browser
xdg-mime default xfe.desktop inode/directory
