#!/bin/bash

# install pacman packages
sudo pacman --needed -S \
    discord             \
    easytag             \
    firefox             \
    gimp                \
    libreoffice-still   \
    steam               \
    tigervnc            \
    vlc                 \
    vlc-plugin-ffmpeg   \
    yt-dlp
