#!/bin/bash

# install pacman packages
sudo pacman --needed -S \
    dnsmasq             \
    iptables-nft        \
    libbsd              \
    libvirt             \
    qemu                \
    virt-manager

# start libvirtd service
sudo systemctl enable --now libvirtd

# add libvirt group to current user 
sudo usermod -aG libvirt $USER
