#!/bin/bash

# install paru packages
paru --needed -S                \
    freetube-bin                \
    heroic-games-launcher-bin   \
    mcomix                      \
    mkinitcpio-firmware         \
    nordvpn-bin                 \
    parsec-bin                  \
    protonup-qt                 \
    sgdboop-bin                 \
    slack-desktop               \
    spotify                     \
    steamlink                   \
    tiny-media-manager          \
    vscodium-bin                \
    xfe                         \
    yed                         \
    zoom

# set default file browser
xdg-mime default xfe.desktop inode/directory
