#!/bin/bash

# install pacman packages
sudo pacman --needed -S \
    archlinux-xdg-menu  \
    awesome             \
    base-devel          \
    bash-completion     \
    calibre             \
    cmake               \
    discord             \
    feh                 \
    ffmpeg              \
    firefox             \
    gimp                \
    git                 \
    gnu-free-fonts      \
    gparted             \
    htop                \
    imagemagick         \
    iw                  \
    iwd                 \
    jellyfin-ffmpeg     \
    jellyfin-server     \
    jellyfin-web        \
    lib32-mesa          \
    lib32-vulkan-radeon \
    libreoffice-still   \
    linux-headers       \
    liquidctl           \
    lsb-release         \
    man-db              \
    man-pages           \
    mesa                \
    mlocate             \
    mtools              \
    noto-fonts          \
    noto-fonts-emoji    \
    ntfs-3g             \
    openssh             \
    p7zip               \
    pavucontrol         \
    qbittorrent         \
    reflector           \
    steam               \
    tk                  \
    unzip               \
    vim                 \
    vulkan-radeon       \
    wget                \
    vlc                 \
    xarchiver           \
    xcompmgr            \
    xdg-user-dirs       \
    xdg-utils           \
    xf86-video-amdgpu   \
    xorg-xrandr         \
    xscreensaver        \
    xterm               \
    zip

# download and build paru
git clone https://aur.archlinux.org/paru.git
cd paru
makepkg -si
cd ..
rm -rf paru

# install paru packages
paru --needed -S                \
    amdgpu_top-bin              \
    freetube-bin                \
    heroic-games-launcher-bin   \
    mcomix                      \
    mkinitcpio-firmware         \
    parsec-bin                  \
    protonup-qt                 \
    sgdboop-bin                 \
    slack-desktop               \
    spotify                     \
    steamlink                   \
    vscodium-bin                \
    xfe                         \
    yed                         \
    zoom

# set default file browser
xdg-mime default xfe.desktop inode/directory
